namespace:
  name: prod
 
service:
  port: 7111

image:
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 128Mi

containerPort: 3111

livenessProbe: /healthz

readinessProbe: /healthz

configmap:
  data: "version: alpine"